create table if not exists user_favorites
(
    id         bigint generated by default as identity,
    created_at timestamp not null default current_timestamp,
    user_id    bigint    not null,
    article_id bigint    not null
)