create table if not exists user_follows
(
    id          bigint generated by default as identity,
    created_at  timestamp not null default current_timestamp,
    follower_id bigint    not null,
    followee_id bigint    not null
)