create table if not exists comments
(
    id         bigint generated by default as identity,
    body       varchar     not null default '',
    user_id    bigint      not null references users (id) on delete cascade,
    article_id bigint      not null references articles (id) on delete cascade,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp
);

alter table comments
    add constraint comments_id_pk primary key (id);
