create table if not exists user_favorites
(
    id         bigint generated by default as identity,
    created_at timestamptz not null default current_timestamp,
    user_id    bigint      not null,
    article_id bigint      not null
);

alter table user_favorites
    add constraint user_favorite_id_pk primary key (id);